packages:
  - apps/*
  - packages/*
  - circuits
  - chain

ignoredBuiltDependencies:
  - '@reown/appkit'

onlyBuiltDependencies:
  - bigint-buffer
  - blake-hash
  - bufferutil
  - cbor-extract
  - secp256k1
  - sharp
  - unrs-resolver
  - utf-8-validate
