/// SatKey Account Contract
///
/// A custom Starknet account that validates transactions using a Zero-Knowledge proof
/// of Bitcoin ECDSA ownership (generated by the Noir satkey_auth circuit and verified
/// by a Garaga-generated UltraHonk verifier contract).

use starknet::ContractAddress;

// ── Garaga verifier interface ─────────────────────────────────────────────────
#[starknet::interface]
trait IGaragaVerifier<TContractState> {
    fn verify_ultra_keccak_zk_honk_proof(
        self: @TContractState,
        full_proof_with_hints: Span<felt252>,
    ) -> Result<Span<u256>, felt252>;
}

// ── Account interface (custom extensions) ─────────────────────────────────────
#[starknet::interface]
trait ISatKeyAccount<TContractState> {
    fn get_nonce(self: @TContractState) -> felt252;
    fn get_verifier_address(self: @TContractState) -> ContractAddress;
    fn get_public_key_salt(self: @TContractState) -> felt252;
    fn execute_from_relayer(
        ref self: TContractState,
        calls: Array<starknet::account::Call>,
        signature: Span<felt252>
    ) -> Array<Span<felt252>>;
}

// ── Contract ──────────────────────────────────────────────────────────────────
#[starknet::contract(account)]
mod SatKeyAccount {
    use super::{IGaragaVerifierDispatcher, IGaragaVerifierDispatcherTrait};
    use super::ISatKeyAccount;
    use openzeppelin_introspection::src5::SRC5Component;
    use openzeppelin_introspection::src5::SRC5Component::InternalTrait as SRC5InternalTrait;
    use starknet::ContractAddress;
    use starknet::account::Call;
    use starknet::get_block_timestamp;
    use starknet::get_tx_info;
    use starknet::syscalls::call_contract_syscall;
    use starknet::storage::{StoragePointerReadAccess, StoragePointerWriteAccess};
    use core::num::traits::Zero;
    use openzeppelin_account::utils::is_tx_version_valid;

    // ── Constants (Standard Interface IDs) ───────────────────────────────────
    const ISRC6_ID: felt252 = 0x2ceccef7f994940b3962a6c67e0ba4fcd37df7d131417c604f91e03caecc1cd;

    // ── Components ───────────────────────────────────────────────────────────
    component!(path: SRC5Component, storage: src5, event: SRC5Event);

    #[abi(embed_v0)]
    impl SRC5Impl = SRC5Component::SRC5Impl<ContractState>;
    impl SRC5InternalImpl = SRC5Component::InternalImpl<ContractState>;

    // ── Storage ───────────────────────────────────────────────────────────────
    #[storage]
    struct Storage {
        verifier_address: ContractAddress,
        nonce: felt252,
        public_key_salt: felt252,
        #[substorage(v0)]
        src5: SRC5Component::Storage,
    }

    // ── Events ────────────────────────────────────────────────────────────────
    #[event]
    #[derive(Drop, starknet::Event)]
    enum Event {
        Authenticated: Authenticated,
        #[flat]
        SRC5Event: SRC5Component::Event,
    }

    #[derive(Drop, starknet::Event)]
    struct Authenticated {
        nonce: felt252,
    }

    // ── Constructor ───────────────────────────────────────────────────────────
    #[constructor]
    fn constructor(
        ref self: ContractState,
        verifier_address: ContractAddress,
        public_key_salt: felt252,
    ) {
        self.verifier_address.write(verifier_address);
        self.public_key_salt.write(public_key_salt);
        self.nonce.write(0);
        
        // Register SNIP-6 (Standard Account)
        self.src5.register_interface(ISRC6_ID);
    }

    // ── Protocol Entrypoints ──────────────────────────────────────────────────
    #[abi(embed_v0)]
    impl AccountContractImpl of starknet::account::AccountContract<ContractState> {
        fn __execute__(ref self: ContractState, calls: Array<Call>) -> Array<Span<felt252>> {
            assert(starknet::get_caller_address().is_zero(), 'Caller must be protocol');
            assert(is_tx_version_valid(), 'Invalid tx version');
            
            let current_nonce = self.nonce.read();
            self.nonce.write(current_nonce + 1);
            self.emit(Authenticated { nonce: current_nonce });

            let mut results: Array<Span<felt252>> = ArrayTrait::new();
            for call in calls {
                results.append(
                    call_contract_syscall(call.to, call.selector, call.calldata).expect('Call failed')
                );
            };
            results
        }

        fn __validate__(ref self: ContractState, calls: Array<Call>) -> felt252 {
            self._verify_and_check(get_tx_info().unbox().signature);
            starknet::VALIDATED
        }

        fn __validate_declare__(self: @ContractState, class_hash: felt252) -> felt252 {
            core::panic_with_felt252('Declare not supported')
        }
    }

    // ── SNIP-6 Compliance ───────────────────────────────────────────────────
    #[starknet::interface]
    trait ISRC6Extras<TContractState> {
        fn is_valid_signature(self: @TContractState, hash: felt252, signature: Array<felt252>) -> felt252;
    }

    #[abi(embed_v0)]
    impl ISRC6ExtrasImpl of ISRC6Extras<ContractState> {
        fn is_valid_signature(
            self: @ContractState, hash: felt252, signature: Array<felt252>
        ) -> felt252 {
            if self._try_verify_and_check(signature.span()) {
                starknet::VALIDATED
            } else {
                0
            }
        }
    }

    // ── SNIP-6 CamelCase Alias ────────────────────────────────────────────
    #[starknet::interface]
    trait ISRC6CamelOnly<TContractState> {
        fn isValidSignature(self: @TContractState, hash: felt252, signature: Array<felt252>) -> felt252;
    }

    #[abi(embed_v0)]
    impl ISRC6CamelOnlyImpl of ISRC6CamelOnly<ContractState> {
        fn isValidSignature(
            self: @ContractState, hash: felt252, signature: Array<felt252>
        ) -> felt252 {
            ISRC6ExtrasImpl::is_valid_signature(self, hash, signature)
        }
    }


    // ── SatKey Custom Interface ───────────────────────────────────────────────
    #[abi(embed_v0)]
    impl ISatKeyAccountImpl of ISatKeyAccount<ContractState> {
        fn get_nonce(self: @ContractState) -> felt252 { self.nonce.read() }
        fn get_verifier_address(self: @ContractState) -> ContractAddress { self.verifier_address.read() }
        fn get_public_key_salt(self: @ContractState) -> felt252 { self.public_key_salt.read() }

        fn execute_from_relayer(
            ref self: ContractState, calls: Array<Call>, signature: Span<felt252>
        ) -> Array<Span<felt252>> {
            self._verify_and_check(signature);
            
            let current_nonce = self.nonce.read();
            self.nonce.write(current_nonce + 1);
            self.emit(Authenticated { nonce: current_nonce });

            let mut results: Array<Span<felt252>> = ArrayTrait::new();
            for call in calls {
                results.append(
                    call_contract_syscall(call.to, call.selector, call.calldata).expect('Call failed')
                );
            };
            results
        }
    }

    // ── Internal Helpers ──────────────────────────────────────────────────────
    #[generate_trait]
    impl InternalImpl of InternalTrait {
        /// Verifies the ZK proof and checks public inputs. Panics on failure.
        /// Signature format: [proof_len, ...proof_felts, ...publicSignals]
        /// We extract proof_len and pass ONLY the proof portion to Garaga verifier.
        fn _verify_and_check(self: @ContractState, signature: Span<felt252>) {
            // Parse signature: [proof_len, proof_felts..., salt, msg_hash, nonce, expiry]
            let proof_len: felt252 = *signature.at(0);
            let proof_len_u32: u32 = proof_len.try_into().expect('proof_len overflow');

            // Extract proof portion: signature[1..1+proof_len]
            let proof_slice = signature.slice(1, proof_len_u32);

            // Call verifier with ONLY the proof (not the appended public signals)
            let public_inputs = self._do_verify(proof_slice);

            // Validate public inputs returned by verifier
            self._check_public_inputs(public_inputs);
        }

        /// Non-panicking verification. Returns true if proof is valid.
        /// Used by is_valid_signature per SNIP-6 spec (must return 0, not panic).
        fn _try_verify_and_check(self: @ContractState, signature: Span<felt252>) -> bool {
            // Parse signature: [proof_len, proof_felts..., salt, msg_hash, nonce, expiry]
            let proof_len: felt252 = *signature.at(0);
            let proof_len_u32: u32 = match proof_len.try_into() {
                Option::Some(v) => v,
                Option::None => { return false; },
            };

            // Extract proof portion: signature[1..1+proof_len]
            let proof_slice = signature.slice(1, proof_len_u32);

            // Call verifier with ONLY the proof
            let verifier = IGaragaVerifierDispatcher {
                contract_address: self.verifier_address.read()
            };
            let verify_result = verifier.verify_ultra_keccak_zk_honk_proof(proof_slice);
            let public_inputs = match verify_result {
                Result::Ok(inputs) => inputs,
                Result::Err(_) => { return false; },
            };

            // Validate public inputs
            if public_inputs.len() != 4 {
                return false;
            }

            // BN254 Poseidon output may exceed Stark prime, reduce it first
            let stark_prime: u256 = 0x0800000000000011000000000000000000000000000000000000000000000001_u256;
            let raw_salt: u256 = *public_inputs.at(0);
            let sig_salt: Option<felt252> = (raw_salt % stark_prime).try_into();
            let sig_nonce: Option<felt252> = (*public_inputs.at(2)).try_into();
            let sig_expiry: Option<felt252> = (*public_inputs.at(3)).try_into();

            let (salt, nonce, expiry) = match (sig_salt, sig_nonce, sig_expiry) {
                (Option::Some(s), Option::Some(n), Option::Some(e)) => (s, n, e),
                _ => { return false; },
            };

            if nonce != self.nonce.read() {
                return false;
            }
            let expiry_u64: Option<u64> = expiry.try_into();
            match expiry_u64 {
                Option::Some(e) => { if e <= get_block_timestamp() { return false; } },
                Option::None => { return false; },
            };
            if salt != self.public_key_salt.read() {
                return false;
            };

            true
        }

        /// Calls the Garaga verifier and returns public inputs. Panics on failure.
        fn _do_verify(self: @ContractState, proof: Span<felt252>) -> Span<u256> {
            let verifier = IGaragaVerifierDispatcher {
                contract_address: self.verifier_address.read()
            };
            let verify_result = verifier.verify_ultra_keccak_zk_honk_proof(proof);
            match verify_result {
                Result::Ok(inputs) => inputs,
                Result::Err(err) => { core::panic_with_felt252(err) },
            }
        }

        /// Checks public inputs against contract state. Panics on mismatch.
        /// Note: message_hash (index 1) is not validated here because the Bitcoin auth message
        /// (nonce + expiry) is separate from the Starknet transaction. The key security property
        /// is that the proof is bound to this account via salt, and nonce/expiry prevent replay.
        fn _check_public_inputs(self: @ContractState, public_inputs: Span<u256>) {
            assert(public_inputs.len() == 4, 'Invalid public inputs length');
            
            // BN254 Poseidon output may exceed Stark prime, reduce it first
            let stark_prime: u256 = 0x0800000000000011000000000000000000000000000000000000000000000001_u256;
            let raw_salt: u256 = *public_inputs.at(0);
            let sig_salt: felt252 = (raw_salt % stark_prime).try_into().expect('salt overflow');

            // message_hash at index 1 is NOT validated - see note above
            let sig_nonce: felt252 = (*public_inputs.at(2)).try_into().expect('nonce overflow');
            let sig_expiry: felt252 = (*public_inputs.at(3)).try_into().expect('expiry overflow');

            assert(sig_nonce == self.nonce.read(), 'Nonce mismatch');
            assert(sig_expiry.try_into().unwrap() > get_block_timestamp(), 'Proof expired');
            assert(sig_salt == self.public_key_salt.read(), 'Salt mismatch');
    }
}
}

