/// SatKey Account Contract
///
/// A custom Starknet account that validates transactions using a Zero-Knowledge proof
/// of Bitcoin ECDSA ownership (generated by the Noir satkey_auth circuit and verified
/// by a Garaga-generated UltraHonk verifier contract).
///
/// Signature layout (passed as `signature` field of INVOKE tx):
///   [proof_len, proof_felts..., salt, message_hash_felt, nonce_felt, expiry_felt]
///
/// Validation logic:
///   1. Deserialise proof + public signals from `signature`.
///   2. Extract nonce + expiry from public signals.
///   3. Assert nonce == stored nonce (replay protection).
///   4. Assert expiry > block timestamp (freshness check).
///   5. Call Garaga verifier → assert result == true.
///   6. (Execute) Increment stored nonce.

use starknet::ContractAddress;

// ── Garaga verifier interface ─────────────────────────────────────────────────
// Garaga v1.0.1 generates a contract with this external entry-point:
//   fn verify_ultra_keccak_zk_honk_proof(
//       full_proof_with_hints: Span<felt252>
//   ) -> Result<Span<u256>, felt252>
//
// Returns Ok(public_inputs) if the proof is valid, Err(error) otherwise.
// `full_proof_with_hints` is the raw proof data + MSM/KZG hints.

#[starknet::interface]
trait IGaragaVerifier<TContractState> {
    fn verify_ultra_keccak_zk_honk_proof(
        self: @TContractState,
        full_proof_with_hints: Span<felt252>,
    ) -> Result<Span<u256>, felt252>;
}

// ── Account interface ─────────────────────────────────────────────────────────
#[starknet::interface]
trait ISatKeyAccount<TContractState> {
    fn get_nonce(self: @TContractState) -> felt252;
    fn get_verifier_address(self: @TContractState) -> ContractAddress;
    fn get_public_key_salt(self: @TContractState) -> felt252;
    fn execute_from_relayer(ref self: TContractState, calls: Array<starknet::account::Call>, signature: Span<felt252>) -> Array<Span<felt252>>;
}

// ── Contract ──────────────────────────────────────────────────────────────────
#[starknet::contract(account)]
mod SatKeyAccount {
    use super::{IGaragaVerifierDispatcher, IGaragaVerifierDispatcherTrait};
    use super::ISatKeyAccount;
    use starknet::ContractAddress;
    use starknet::account::Call;
    use starknet::get_block_timestamp;
    use starknet::get_tx_info;
    use starknet::syscalls::call_contract_syscall;
    use starknet::storage::{StoragePointerReadAccess, StoragePointerWriteAccess};
    use core::num::traits::Zero;

    // ── Storage ───────────────────────────────────────────────────────────────
    #[storage]
    struct Storage {
        /// Address of the deployed Garaga verifier contract
        verifier_address: ContractAddress,
        /// Monotonically increasing nonce — must match proof's nonce signal
        nonce: felt252,
        /// Poseidon(pubkey_x, pubkey_y, DOMAIN_TAG) — used to bind account to BTC pubkey
        public_key_salt: felt252,
    }

    // ── Events ────────────────────────────────────────────────────────────────
    #[event]
    #[derive(Drop, starknet::Event)]
    enum Event {
        Authenticated: Authenticated,
    }

    #[derive(Drop, starknet::Event)]
    struct Authenticated {
        nonce: felt252,
    }

    // ── Constructor ───────────────────────────────────────────────────────────
    #[constructor]
    fn constructor(
        ref self: ContractState,
        verifier_address: ContractAddress,
        public_key_salt: felt252,
    ) {
        self.verifier_address.write(verifier_address);
        self.public_key_salt.write(public_key_salt);
        self.nonce.write(0);
    }

    // ── SNIP-6 Account interface ──────────────────────────────────────────────
    #[abi(embed_v0)]
    impl SatKeyAccountImpl of starknet::account::AccountContract<ContractState> {
        /// Called by the Starknet sequencer to validate a transaction.
        /// The `signature` field of the tx contains the ZK proof + public signals.
        fn __validate__(ref self: ContractState, calls: Array<Call>) -> felt252 {
            let tx_info = get_tx_info().unbox();
            self._verify_and_check(tx_info.signature);
            starknet::VALIDATED
        }
        fn __validate_declare__(
            self: @ContractState,
            class_hash: felt252,
        ) -> felt252 {
            // Only the account owner (via ZK proof) can declare — not supported in this MVP
            core::panic_with_felt252('Declare not supported')
        }

        fn __execute__(
            ref self: ContractState,
            calls: Array<Call>,
        ) -> Array<Span<felt252>> {
            // Only callable by the Starknet protocol after __validate__ succeeds
            assert(
                starknet::get_caller_address().is_zero(),
                'Caller must be protocol'
            );

            // Increment nonce after successful validation
            let current_nonce = self.nonce.read();
            self.nonce.write(current_nonce + 1);

            // Emit authentication event
            self.emit(Authenticated { nonce: current_nonce });

            // Execute each call
            let mut results: Array<Span<felt252>> = ArrayTrait::new();
            for call in calls {
                let result = call_contract_syscall(
                    call.to,
                    call.selector,
                    call.calldata,
                )
                    .expect('Call failed');
                results.append(result);
            };
            results
        }
    }

    // ── View functions ────────────────────────────────────────────────────────
    #[abi(embed_v0)]
    impl ISatKeyAccountImpl of ISatKeyAccount<ContractState> {
        fn get_nonce(self: @ContractState) -> felt252 {
            self.nonce.read()
        }

        fn get_verifier_address(self: @ContractState) -> ContractAddress {
            self.verifier_address.read()
        }

        fn get_public_key_salt(self: @ContractState) -> felt252 {
            self.public_key_salt.read()
        }

        fn execute_from_relayer(
            ref self: ContractState,
            calls: Array<Call>,
            signature: Span<felt252>
        ) -> Array<Span<felt252>> {
            // Authenticate using the provided signature
            self._verify_and_check(signature);

            // Increment nonce after successful validation
            let current_nonce = self.nonce.read();
            self.nonce.write(current_nonce + 1);

            // Emit authentication event
            self.emit(Authenticated { nonce: current_nonce });

            // Execute each call
            let mut results: Array<Span<felt252>> = ArrayTrait::new();
            for call in calls {
                let result = call_contract_syscall(
                    call.to,
                    call.selector,
                    call.calldata,
                ).expect('Call failed');
                results.append(result);
            };
            results
        }
    }

    // ── Internal Helpers ──────────────────────────────────────────────────────
    #[generate_trait]
    impl InternalImpl of InternalTrait {
        fn _verify_and_check(self: @ContractState, signature: Span<felt252>) {
            // ── ZK proof verification via Garaga ─────────────────────────────
            let verifier = IGaragaVerifierDispatcher {
                contract_address: self.verifier_address.read()
            };
            let verify_result = verifier.verify_ultra_keccak_zk_honk_proof(signature);
            let public_inputs = match verify_result {
                Result::Ok(inputs) => inputs,
                Result::Err(err) => {
                    core::panic_with_felt252(err)
                },
            };

            // Circuit returns 4 public inputs: [salt, message_hash, nonce, expiry]
            assert(public_inputs.len() == 4, 'Invalid public inputs length');

            let sig_salt: felt252 = (*public_inputs.at(0)).try_into().expect('salt overflow');
            let _msg_hash: felt252 = (*public_inputs.at(1)).try_into().expect('msg_hash overflow');
            let sig_nonce: felt252 = (*public_inputs.at(2)).try_into().expect('nonce overflow');
            let sig_expiry: felt252 = (*public_inputs.at(3)).try_into().expect('expiry overflow');

            // ── Replay protection ────────────────────────────────────────────
            let stored_nonce = self.nonce.read();
            assert(sig_nonce == stored_nonce, 'Nonce mismatch');

            // ── Freshness check ───────────────────────────────────────────────
            let block_ts: felt252 = get_block_timestamp().into();
            let expiry_u64: u64 = sig_expiry.try_into().expect('expiry overflow');
            let ts_u64: u64 = block_ts.try_into().expect('timestamp overflow');
            assert(expiry_u64 > ts_u64, 'Proof expired');

            // ── Salt binding: proof must use this account's salt ─────────────
            let stored_salt = self.public_key_salt.read();
            assert(sig_salt == stored_salt, 'Salt mismatch');
        }
    }
}
