/**
 * witness.ts
 *
 * Builds a Prover.toml string from the prove request body.
 * All byte arrays are BIG-ENDIAN (matching Noir [u8; 32] inputs).
 *
 * BIG-ENDIAN rule: felt = Σ byte[i] * 256^(31-i)
 */

export interface ProveRequest {
  /** Compressed (33-byte) or uncompressed (65-byte) hex pubkey — 0x-prefixed or not */
  pubkey: string;
  /** ECDSA r component — 0x-prefixed hex, 32 bytes */
  signature_r: string;
  /** ECDSA s component — 0x-prefixed hex, 32 bytes */
  signature_s: string;
  /** SHA-256 message hash — 0x-prefixed hex, 32 bytes */
  message_hash: string;
  /** Timestamp-based nonce string (decimal or hex) */
  nonce: string;
  /** Expiry timestamp string (decimal or hex) */
  expiry: string;
}

const STARK_FIELD_PRIME = BigInt(
  "0x0800000000000011000000000000000000000000000000000000000000000001"
);

/** Strip 0x prefix and return lowercase hex */
function stripHex(s: string): string {
  return s.startsWith("0x") || s.startsWith("0X") ? s.slice(2) : s;
}

/** Pad hex string to exactly `len` bytes (2*len chars) */
function padHex(hex: string, len: number): string {
  return hex.toLowerCase().padStart(len * 2, "0");
}

/** Convert a 32-byte big-endian hex string to a TOML array of decimal u8 values */
function hexToTomlArray(hex: string): string {
  const h = padHex(stripHex(hex), 32);
  const bytes: number[] = [];
  for (let i = 0; i < 64; i += 2) {
    bytes.push(parseInt(h.slice(i, i + 2), 16));
  }
  return `[${bytes.join(", ")}]`;
}

/** Decompress secp256k1 compressed pubkey into (x, y) as 32-byte big-endian hex strings */
function decompressPubkey(pubkeyHex: string): { x: string; y: string } {
  const clean = stripHex(pubkeyHex).toLowerCase();

  // Uncompressed: 04 + 32-byte x + 32-byte y = 130 hex chars
  if (clean.length === 130 && clean.startsWith("04")) {
    return {
      x: clean.slice(2, 66),
      y: clean.slice(66, 130),
    };
  }

  if (clean.length === 64) {
    // 32-byte x-coordinate only (Taproot/Schnorr pubkey format)
    // For ECDSA we need the full pubkey, but some wallets only expose the x-coord
    // We'll throw a more helpful error
    throw new Error(`Wallet provided an x-coordinate only pubkey (64 chars). Our ECDSA circuit requires a full compressed (66 chars) or uncompressed (130 chars) public key.`);
  }

  if (clean.length !== 66) {
    throw new Error(
      `Invalid pubkey hex length ${clean.length}. Expected 66 (compressed) or 130 (uncompressed).`
    );
  }

  const prefix = clean.slice(0, 2);
  if (prefix !== "02" && prefix !== "03") {
    throw new Error(`Invalid compressed pubkey prefix: ${prefix}`);
  }

  // secp256k1: y² = x³ + 7 (mod P)
  const P =
    0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2fn;
  const x = BigInt("0x" + clean.slice(2));
  const y2 = (x ** 3n + 7n) % P;

  // Tonelli-Shanks shortcut: P ≡ 3 (mod 4) → sqrt = y2^((P+1)/4) mod P
  let y = modPow(y2, (P + 1n) / 4n, P);

  const isOdd = prefix === "03";
  if ((y & 1n) !== (isOdd ? 1n : 0n)) {
    y = P - y;
  }

  return {
    x: x.toString(16).padStart(64, "0"),
    y: y.toString(16).padStart(64, "0"),
  };
}

function modPow(base: bigint, exp: bigint, mod: bigint): bigint {
  let result = 1n;
  base = base % mod;
  while (exp > 0n) {
    if (exp & 1n) result = (result * base) % mod;
    exp >>= 1n;
    base = (base * base) % mod;
  }
  return result;
}

/** Convert a decimal/hex string timestamp to a STARK-field felt hex */
function timestampToFelt(value: string): string {
  const n =
    value.startsWith("0x") || value.startsWith("0X")
      ? BigInt(value)
      : BigInt(value);
  const felt = n % STARK_FIELD_PRIME;
  return "0x" + felt.toString(16);
}

/**
 * Build Prover.toml content from a ProveRequest.
 * Returns a TOML string ready to write to disk.
 */
export function buildProverToml(req: ProveRequest): string {
  const { x, y } = decompressPubkey(req.pubkey);

  const pubkey_x = hexToTomlArray(x);
  const pubkey_y = hexToTomlArray(y);
  const sig_r = hexToTomlArray(req.signature_r);
  const sig_s = hexToTomlArray(req.signature_s);
  const message_hash = hexToTomlArray(req.message_hash);
  const nonce = timestampToFelt(req.nonce);
  const expiry = timestampToFelt(req.expiry);

  return [
    `# Auto-generated by satkey prover service — DO NOT EDIT`,
    `pubkey_x    = ${pubkey_x}`,
    `pubkey_y    = ${pubkey_y}`,
    `sig_r       = ${sig_r}`,
    `sig_s       = ${sig_s}`,
    `message_hash = ${message_hash}`,
    `nonce       = "${nonce}"`,
    `expiry      = "${expiry}"`,
  ].join("\n");
}
