/**
 * witness.ts
 *
 * Builds a Prover.toml string from the prove request body.
 * All byte arrays are BIG-ENDIAN (matching Noir [u8; 32] inputs).
 */

export interface ProveRequest {
  pubkey: string;
  nonce: string;
  expiry: string;
}

const STARK_FIELD_PRIME = BigInt(
  "0x0800000000000011000000000000000000000000000000000000000000000001"
);

function stripHex(s: string): string {
  return s.startsWith("0x") || s.startsWith("0X") ? s.slice(2) : s;
}

function padHex(hex: string, len: number): string {
  return hex.toLowerCase().padStart(len * 2, "0");
}

function hexToTomlArray(hex: string): string {
  const h = padHex(stripHex(hex), 32);
  const bytes: number[] = [];
  for (let i = 0; i < 64; i += 2) {
    bytes.push(parseInt(h.slice(i, i + 2), 16));
  }
  return `[${bytes.join(", ")}]`;
}

function modPow(base: bigint, exp: bigint, mod: bigint): bigint {
  let result = 1n;
  base = base % mod;
  while (exp > 0n) {
    if (exp & 1n) result = (result * base) % mod;
    exp >>= 1n;
    base = (base * base) % mod;
  }
  return result;
}

export function decompressPubkey(pubkeyHex: string): { x: string; y: string } {
  const clean = stripHex(pubkeyHex).toLowerCase();

  if (clean.length === 130 && clean.startsWith("04")) {
    return {
      x: clean.slice(2, 66),
      y: clean.slice(66, 130),
    };
  }

  if (clean.length === 64) {
    throw new Error(`Wallet provided an x-coordinate only pubkey (64 chars). Our ECDSA circuit requires a full compressed (66 chars) or uncompressed (130 chars) public key.`);
  }

  if (clean.length !== 66) {
    throw new Error(
      `Invalid pubkey hex length ${clean.length}. Expected 66 (compressed) or 130 (uncompressed).`
    );
  }

  const prefix = clean.slice(0, 2);
  if (prefix !== "02" && prefix !== "03") {
    throw new Error(`Invalid compressed pubkey prefix: ${prefix}`);
  }

  const P =
    0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2fn;
  const x = BigInt("0x" + clean.slice(2));
  const y2 = (x ** 3n + 7n) % P;

  let y = modPow(y2, (P + 1n) / 4n, P);

  const isOdd = prefix === "03";
  if ((y & 1n) !== (isOdd ? 1n : 0n)) {
    y = P - y;
  }

  return {
    x: x.toString(16).padStart(64, "0"),
    y: y.toString(16).padStart(64, "0"),
  };
}

function timestampToFelt(value: string): string {
  const n = BigInt(value.startsWith("0x") || value.startsWith("0X") ? value : value);
  const felt = n % STARK_FIELD_PRIME;
  return "0x" + felt.toString(16);
}

export function buildProverToml(req: ProveRequest): string {
  const { x, y } = decompressPubkey(req.pubkey);

  const pubkey_x = hexToTomlArray(x);
  const pubkey_y = hexToTomlArray(y);
  
  const nonce = timestampToFelt(req.nonce);
  const expiry = timestampToFelt(req.expiry);

  return [
    `# Auto-generated by satkey prover service — DO NOT EDIT`,
    `pubkey_x    = ${pubkey_x}`,
    `pubkey_y    = ${pubkey_y}`,
    `nonce       = "${nonce}"`,
    `expiry      = "${expiry}"`,
  ].join("\n");
}
